# Generated by Django 4.1.1 on 2022-09-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=128)),
                ('edad', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
            ],
        ),
    ]
